name: SCA Agent-Based Scan Script
on: 
  workflow_dispatch:

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: SCA Agent-Based Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: SCA Agent Scan
        run: |
             export SRCCLR_API_TOKEN=${{ secrets.SRCCLR_API_TOKEN }}
             curl -sSL https://download.sourceclear.com/ci.sh | bash -s - scan --update-advisor --recursive
